export const sampleTenders = [
  {
    id: 'GEM/2026/B/4521',
    title: 'IT Hardware — 500 Desktop Computers',
    department: 'Ministry of Defence',
    category: 'IT Hardware',
    estimatedValue: '₹4.25 Cr',
    status: 'evaluating',
    bidsCount: 8,
    evalProgress: 65,
    createdAt: '2026-05-15',
    deadline: '2026-06-15',
    emd: '₹8,50,000',
  },
  {
    id: 'CPP/2026/S/892',
    title: 'Cloud Infrastructure Services — MeitY',
    department: 'MeitY',
    category: 'IT Services',
    estimatedValue: '₹12.8 Cr',
    status: 'open',
    bidsCount: 3,
    evalProgress: 0,
    createdAt: '2026-05-20',
    deadline: '2026-07-01',
    emd: '₹25,60,000',
  },
  {
    id: 'GEM/2026/B/4498',
    title: 'Office Furniture — 200 Units',
    department: 'Ministry of Home Affairs',
    category: 'Furniture',
    estimatedValue: '₹85 L',
    status: 'completed',
    bidsCount: 12,
    evalProgress: 100,
    createdAt: '2026-04-10',
    deadline: '2026-05-10',
    emd: '₹1,70,000',
    l1Bidder: 'Godrej Interio',
    l1Amount: '₹72.4L',
  },
  {
    id: 'GEM/2026/B/4535',
    title: 'CCTV Security Camera System',
    department: 'Ministry of Defence',
    category: 'Security Equipment',
    estimatedValue: '₹1.6 Cr',
    status: 'draft',
    bidsCount: 0,
    evalProgress: 0,
    createdAt: '2026-05-28',
    deadline: null,
    emd: '₹3,20,000',
  },
];

export const sampleBidders = [
  {
    id: 1,
    name: 'HP India Pvt Ltd',
    type: 'Large',
    localClass: 'Class 1 Local',
    msme: false,
    scores: { specMatch: 28, experience: 14, warranty: 13, delivery: 7, total: 62 },
    totalBid: '₹3.92 Cr',
    rank: 1,
    evidence: {
      specMatch: { quote: 'Intel Core i5-13400 processor, 10 cores, 16 threads, up to 4.6GHz', page: 4 },
      experience: { quote: '5 completed orders for MoD, DRDO, and MHA totaling ₹22 Cr in last 3 years', page: 12 },
      warranty: { quote: '3-year on-site comprehensive warranty with 4-hour response SLA', page: 8 },
    },
  },
  {
    id: 2,
    name: 'Dell Technologies India',
    type: 'Large',
    localClass: 'Class 1 Local',
    msme: false,
    scores: { specMatch: 27, experience: 13, warranty: 14, delivery: 6, total: 60 },
    totalBid: '₹4.05 Cr',
    rank: 2,
    evidence: {
      specMatch: { quote: 'Intel Core i5-13500 vPro processor, 14 cores, 20 threads', page: 5 },
      experience: { quote: '4 government orders in last 2 years including ISRO and NIC', page: 14 },
      warranty: { quote: '3-year ProSupport Plus with next business day on-site service', page: 9 },
    },
  },
  {
    id: 3,
    name: 'Acer India Ltd',
    type: 'Large',
    localClass: 'Class 2 Local',
    msme: false,
    scores: { specMatch: 24, experience: 11, warranty: 12, delivery: 5, total: 52 },
    totalBid: '₹3.68 Cr',
    rank: 3,
    evidence: {
      specMatch: { quote: 'AMD Ryzen 5 5600G processor, 6 cores, 12 threads', page: 3 },
      experience: { quote: '2 government orders — UP Police and Bihar Education Dept', page: 10 },
      warranty: { quote: '3-year limited warranty with depot service', page: 7 },
    },
  },
  {
    id: 4,
    name: 'CompuTech Solutions',
    type: 'MSME',
    localClass: 'Micro',
    msme: true,
    scores: { specMatch: 22, experience: 9, warranty: 11, delivery: 5, total: 47 },
    totalBid: '₹3.55 Cr',
    rank: 4,
    evidence: {
      specMatch: { quote: 'Intel Core i5-12400 processor, 6 cores, assembled system', page: 4 },
      experience: { quote: '1 state government order — Rajasthan IT Department, 100 units', page: 8 },
      warranty: { quote: '3-year parts warranty, on-site service in Delhi NCR only', page: 6 },
    },
  },
  {
    id: 5,
    name: 'TechVista Enterprises',
    type: 'MSME',
    localClass: 'Small',
    msme: true,
    scores: { specMatch: 20, experience: 8, warranty: 10, delivery: 5, total: 43 },
    totalBid: '₹3.42 Cr',
    rank: 5,
    evidence: {
      specMatch: { quote: 'Intel Core i5-12400F, 16GB DDR4, 512GB SATA SSD', page: 3 },
      experience: { quote: 'First government tender — 50 desktops to municipal corporation', page: 6 },
      warranty: { quote: '2-year standard warranty with option to extend', page: 5 },
    },
  },
];

export const evaluationCriteria = [
  { name: 'CPU specification (i5 12th gen+)', weight: 10, maxScore: 10, category: 'Technical Specs' },
  { name: 'RAM specification (16GB DDR4+)', weight: 10, maxScore: 10, category: 'Technical Specs' },
  { name: 'SSD specification (512GB NVMe)', weight: 10, maxScore: 10, category: 'Technical Specs' },
  { name: 'Past experience (3+ similar orders)', weight: 15, maxScore: 15, category: 'Experience' },
  { name: 'Warranty & support terms', weight: 15, maxScore: 15, category: 'Support' },
  { name: 'Delivery timeline commitment', weight: 10, maxScore: 10, category: 'Logistics' },
];

export const complianceChecks = [
  { rule: 'GFR 2017 Rule 144', description: 'Valid procurement method selected', status: 'pass' },
  { rule: 'GFR 2017 Rule 153', description: 'Minimum bid submission period (21 days)', status: 'pass' },
  { rule: 'GFR 2017 Rule 161', description: 'EMD within prescribed limits (2-3%)', status: 'pass' },
  { rule: 'GFR 2017 Rule 170', description: 'Award to L1 unless technically justified', status: 'pending' },
  { rule: 'MSME Order 2018', description: '25% procurement reservation for MSMEs', status: 'pass' },
  { rule: 'DPIIT Make-in-India', description: 'Local content preference applied', status: 'pass' },
  { rule: 'CVC Guidelines', description: 'Tender committee properly constituted', status: 'pass' },
];

export const activityLog = [
  { type: 'success', text: 'Evaluation complete — Office Furniture tender. L1: Godrej Interio at ₹72.4L', time: '2 hours ago' },
  { type: 'info', text: 'New bid received — TCS submitted bid for Cloud Infrastructure tender', time: '4 hours ago' },
  { type: 'warning', text: 'Document verification — 3 MSME certificates verified for IT Hardware tender', time: '6 hours ago' },
  { type: 'purple', text: 'RFP generated — Security Cameras draft created via AI assistant', time: 'Yesterday' },
  { type: 'info', text: 'Pre-qualification complete — 8/8 bidders passed for IT Hardware', time: 'Yesterday' },
];
